// Every short string of the Learn section that is not part of a structured
// content module: labels and buttons of the Learn dialog, the templates of
// the static pages, the words inside the Intuition diagrams, frequency
// phrases. Each is its own English key, the way i18n.ts works for the
// rest of the interface; {name} marks a placeholder. A locale translates
// every one of them (tests/learnLocale.test.ts).
export const LEARN_STRINGS = [
  // the technique list
  'Search {n} techniques',
  'Search techniques',
  'Order of the list',
  'Technique families',
  'No technique matches “{q}”.',
  'By family',
  'Easiest first',
  'Most often needed',
  'Most often needed first',
  'Most worth learning',
  'Most worth learning first',
  'In the order the solver tries them: a technique is only needed once everything above it has run dry.',
  'The techniques that turn up in the most puzzles sudokUI generates, whatever their difficulty.',
  'How often a technique is needed, weighted by its rating cost. Difficulty and frequency are different things: a hard technique that turns up often repays the effort of learning it, and those come first.',
  'Learn next',
  'Learn next first',
  'The techniques most worth learning that you have used least on your own. Every move you make is credited with the easiest technique that justifies it, and a technique you have played unaided moves down the list. Your play stays on this device.',
  'Your play: {n} unaided, {h} from hints',
  "Added to a puzzle's rating each time the solver needs this technique",
  'Needed in {freq}',
  'Never needed',
  'Why it works',
  'How to spot it',
  'Needed in {freq} that sudokUI generates.',
  'Also called {list}.',
  'Practice this technique',
  'Scan the running game for this technique (counts as assistance)',
  'Is it on my board?',
  'Open as a page ↗',
  'Worked example',
  '{name} example on a sudoku board',
  'Puzzle: {credit}.',
  'In this puzzle the position comes after harder steps.',
  'Open this position on the board',
  'The solver uses this on the hardest puzzles. It has no pattern to spot, so it is not offered in practice.',
  'Implemented, but never needed: an easier technique always reaches the same result first.',
  'Only ever needed in puzzles made by hand for it: none can be generated, so it is not offered in practice.',
  'Not implemented in sudokUI: the chain engines already find everything it can.',
  // the glossary
  'Glossary: {term}',
  'The words sudoku solvers use, and that the hints in sudokUI use, each defined once.',
  'See',
  'In English: {term}',
  // the Intuition guide
  'Ideas on this page',
  "Explain it like I'm 12",
  'In the catalogue',
  // the rating
  'How fast is fast?',
  'Slow',
  'Typical',
  'Fast',
  'Expert',
  'World class',
  'above {n}',
  'up to {n}',
  'Slow is where the slowest fifth begins. Typical is the median solver. Fast is faster than four solvers in five, Expert faster than 99 in 100, World class faster than 999 in 1,000.',
  'The app says where each of your solves lands.',
  // frequencies
  'fewer than 1 in {n} puzzles',
  'every puzzle',
  '{p}% of puzzles',
  '1 in {n} puzzles',
  // the Intuition diagrams
  'Where 5 can go',
  'The same, by row',
  'row {n}',
  'row',
  'columns',
  'Naked triple: three cells in one row',
  'Bent triple: an XY-Wing',
  'An X-Wing on 5, and the same 5s listed by row as a naked pair',
  'A naked triple and a hidden quad in the same row',
  'A naked triple in one row, and the same three digits bent round a corner as an XY-Wing',
  'A 2-String Kite on 4',
  'A Unique Rectangle in rows 1 and 2, columns 1 and 4',
  // static pages: frame
  'Techniques',
  'Intuition',
  'Glossary',
  'Rating',
  'Play',
  'Learn',
  'Language',
  'sudokUI is a free, open-source sudoku app: no ads, no account, works offline.',
  'Play at sudokui.app',
  'Source on GitHub',
  'Difficulty rating',
  'Sudoku techniques',
  // static pages: a technique
  '{name}: sudoku technique explained',
  '{what} Why it works, how to spot it, and a puzzle to practise on.',
  'How the {name} works in sudoku: the pattern, why it is valid and how to spot it. {level} technique, rating score {score}.',
  '{name} in sudoku',
  'rating cost {score}',
  'also called {list}',
  'how it fits',
  "Step {n} of this puzzle's solution, found and verified by the sudokUI engine. Cells are named by row and column: r2c3 is row 2, column 3.",
  'In this puzzle the position comes after steps harder than the technique itself.',
  'Play this puzzle from the start',
  'Open the guide in sudokUI',
  'Practise it on a real puzzle.',
  'sudokUI generates a puzzle that needs {name} and takes you straight to the position where it applies. Hints draw the pattern on the board and explain the step.',
  'Practice {name}',
  "Open in the app's guide",
  "In a puzzle's rating",
  "Each time the solver needs {name}, the puzzle's difficulty rating grows by {score}. Its class is {level}.",
  'It is needed in {freq} that sudokUI generates.',
  'How the rating works',
  'More {family}',
  // static pages: the technique index
  'Sudoku solving techniques: all {n} explained',
  'All {n} sudoku solving techniques explained in plain words, from Naked Single to Exocet, grouped by family. Practise each one free in the app.',
  'Sudoku solving techniques',
  "All {n} solving techniques in sudokUI's catalogue, grouped by the idea behind them. Each one says what the pattern is, why it works and how to spot it.",
  'Play sudokUI',
  'How they fit together',
  'How rating works',
  'Worth learning first',
  'How often a technique is needed, weighted by its rating cost, over the {sample} puzzles sudokUI has generated and rated. Difficulty and frequency are different things: a hard technique that turns up often repays the effort of learning it.',
  '{level}, needed in {freq}',
  // static pages: the glossary
  'Sudoku glossary: every solving term explained',
  'Plain-English definitions of sudoku solving terms: candidates, strong and weak links, conjugate pairs, almost locked sets, fins, deadly patterns and more.',
  'Sudoku glossary',
  "The words sudoku solvers use, and that sudokUI's hints use, each defined once and precisely.",
  'also {list}',
  'See the terms at work: {techniques}, or {play} and ask for a hint.',
  'every technique explained',
  'play sudokUI',
  // static pages: the Intuition guide
  'How sudoku techniques fit together',
  'Every sudoku technique comes down to three ideas: locked sets, almost locked sets and chains. Each one explained simply, plus where the names came from.',
  'In the catalogue:',
  'Open in the app',
  'All techniques',
  // static pages: the rating
  'Sudoku difficulty rating: how hard is your puzzle?',
  'How sudoku difficulty is rated: HoDoKu-compatible technique scores, eight bands from Beginner to Nightmare and the full score table. Rate any puzzle free.',
  'Sudoku difficulty rating',
  'Rate your own sudoku',
  'Rate this puzzle',
  'Paste a puzzle: 81 characters, with 0 or . for empty cells',
  'This box needs JavaScript. You can also {open} and choose Import.',
  'open sudokUI',
  'A puzzle needs exactly 81 cells. This one has {n}.',
  'The puzzle opens in sudokUI with its rating and band in the top bar. Nothing is uploaded: the rating is computed on your own device. No string at hand? {open}, choose New, then Custom, and type the puzzle onto the board. See also {hodoku}.',
  'Open sudokUI',
  'how this compares with HoDoKu',
  'The eight difficulty bands',
  'Band',
  'Total score',
  'Typical techniques',
  'Score of every technique',
  "The cost added to a puzzle's rating each time the solver needs the technique, and how many of the puzzles sudokUI generates need it at least once (measured on {sample} puzzles).",
  'Technique',
  'Class',
  'Score',
  'Needed in',
  // static pages: How the best solve
  'Every technique explained',
  'How the difficulty rating works'
] as const;

export type LearnString = (typeof LEARN_STRINGS)[number];

/** fill {name} placeholders */
export function fill(text: string, vars?: Record<string, string | number>): string {
  if (!vars) return text;
  return text.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? String(vars[k]) : m));
}
